workerPoolSpecs:
  machineSpec:
    machineType: n1-highmem-2
  replicaCount: 1
  containerSpec:
    imageUri: europe-west1-docker.pkg.dev/dtumlops-484109/projectregistry/mlops-image:latest
    env:
      - name: WANDB_API_KEY
        value: "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"
      - name: WANDB_ENTITY
        value: "s224381-dtu"
    args:
      - --data_dir
      - /gcs/mlopsproject-data/PokemonData
      - --max_epochs
      - "5"
      - --batch_size
      - "32"
      - --num_workers
      - "2"
