name: Unit Tests

on:
  push:
    branches: [main, gertrud]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ["macos-latest"]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Use matrix python in uv
        run: uv python pin ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev --locked

      - name: Tests (with coverage)
        run: |
          uv run coverage run -m pytest tests/
          uv run coverage report -m
concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true